#Minecraft server properties
#Wed Oct 22 17:54:40 CST 2025
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=2
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=false
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=0
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-enabled-packs=vanilla
level-name=SaphNyaLevel
level-type=bclib\:normal
max-build-height=256
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=Have a cozy stay ^u^
network-compression-threshold=512
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=16489766524865
rcon.port=25575
require-resource-pack=false
server-port=25565
simulation-distance=3
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
use-native-transport=true
view-distance=7
white-list=true



